name: Build and deploy

on:
    release:
        types: [published]

jobs:
    build:
        strategy:
            matrix:
                platform: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 16
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - name: Build and release
              run: |
                  npm install
                  npm run release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
